Split up build steps.

diff --git a/.github/actions/telink/tlsr825x/build/action.yml b/.github/actions/telink/tlsr825x/build/action.yml
--- a/.github/actions/telink/tlsr825x/build/action.yml
+++ b/.github/actions/telink/tlsr825x/build/action.yml
@@ -21,14 +21,23 @@ env:
 runs:
   using: "composite"
   steps:
+    - name: Find eclipsec
+      shell: pwsh
+      run: |
+        $eclipsec=Get-ChildItem -Path "${{ inputs.ide }}\eclipsec.exe" -Recurse | Select FullName
+        if ($eclipsec.count > 1)
+          Write-Error "Multiple instances of 'eclipsec' were found." -ErrorAction:Continue
+          Get-ChildItem -Path "${{ inputs.ide }}\eclipsec.exe" -Recurse | Select FullName
+          exit 1
+        }
+        # Passing result to the next step.
+        echo "eclipsec=$eclipsec" >> $env:GITHUB_ENV
+
     - name: Build TLSR8258 ZigBee image
       shell: pwsh
       run: |
-        $eclipsec=Get-ChildItem -Path "${{ inputs.ide }}\eclipsec.exe" -Recurse
-        $eclipsec
-        # Run eclipsec, waiting for it to complte, redirecting output etc.
         $proc=Start-Process `
-          -FilePath $eclipsec[0].FullName `
+          -FilePath $env:eclipsec `
           -ArgumentList `
             "-vm `
             ""${{ inputs.ide }}\jre\bin\client"" `
@@ -41,7 +50,17 @@ runs:
           -RedirectStandardError $env:TEMP\stderr.txt `
           -Wait `
           -PassThru
-        Write-Information "eclipsec exit code: $($proc.ExitCode.ToString())" -InformationAction:Continue
+
+        # Check exit code.
+        if ($proc.ExitCode -ne 0)
+        {
+          Write-Error "eclipsec exited with $proc.ExitCode." -ErrorAction:Continue
+          exit 1
+        }
+
+    - name: Check for errors and expected files
+      shell: pwsh
+      run:
         # Display output, especially any errors!
         Write-Information "STDOUT from the installer..." -InformationAction:Continue
         Get-Content -Path $env:TEMP\stdout.txt
@@ -53,26 +72,21 @@ runs:
         Remove-Item -Path $env:TEMP\stderr.txt
 
         # Builds worked it all of the following are true:
-        # - ExitCode is zero (0)
+        # - ExitCode is zero (0) (checked above)
         # - stderr log output is empty
         # - an 'elf' image has been created
-        $image_root =
-        if ($proc.ExitCode -ne 0)
-        {
-          Write-Error "eclipsec exited with $proc.ExitCode." -ErrorAction:Continue
-          exit 1
-        }
-        elseif ($stderr -ne "")
+        $image_root = ${{ inputs.zigbee_sdk }}\$env:WORKSPACES\$env:PROJECT_ROOT\${{ inputs.project }}
+        if ($stderr -ne "")
         {
           Write-Error "eclipsec reported errors." -ErrorAction:Continue
           exit 1
         }
-        elseif ((! $(Test-Path -Path ${{ inputs.zigbee_sdk }}\$env:WORKSPACES\$env:PROJECT_ROOT\${{ inputs.project }}\${{ inputs.project }}.elf) -or
-                (! $(Test-Path -Path ${{ inputs.zigbee_sdk }}\$env:WORKSPACES\$env:PROJECT_ROOT\${{ inputs.project }}\${{ inputs.project }}.bin) -or
-                (! $(Test-Path -Path ${{ inputs.zigbee_sdk }}\$env:WORKSPACES\$env:PROJECT_ROOT\${{ inputs.project }}\${{ inputs.project }}.lst))
+        elseif ((! $(Test-Path -Path $image_root\${{ inputs.project }}.elf) -or
+                (! $(Test-Path -Path $image_root\${{ inputs.project }}.bin) -or
+                (! $(Test-Path -Path $image_root\${{ inputs.project }}.lst))
         {
           Write-Error "eclipsec did not generate all expected files." -ErrorAction:Continue
-          Get-ChildItem -Path "${{ inputs.zigbee_sdk }}\$env:WORKSPACES\$env:PROJECT_ROOT\${{ inputs.project }}\${{ inputs.project }}.*"
+          Get-ChildItem -Path "$image_root\${{ inputs.project }}.*"
           exit 1
         }
         else
